# Generated by Django 6.0.6 on 2026-06-17 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DiagnosisReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symptoms', models.TextField()),
                ('condition', models.CharField(max_length=100)),
                ('diagnosis', models.TextField()),
                ('specialist', models.CharField(max_length=100)),
                ('severity', models.CharField(max_length=30)),
                ('urgency', models.CharField(max_length=30)),
                ('confidence', models.IntegerField()),
                ('first_aid', models.TextField()),
                ('tests', models.JSONField(default=list)),
                ('medicines', models.JSONField(default=list)),
                ('home_remedies', models.JSONField(default=list)),
                ('address', models.CharField(blank=True, max_length=300)),
                ('pincode', models.CharField(blank=True, max_length=20)),
                ('hospital_names', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
